picom -b

# xset +fp /home/mbrc/.local/share/fonts/misc/
# xset fp rehash
xrdb ~/.Xresources

feh --bg-tile ~/media/pictures/wp-birdstile.png

# /home/$USER/software/dwm-bar/dwm_bar.sh &
exec ~/software/dwm-simple-bar/dwm-bar & 


exec dbus-launch --sh-syntax --exit-with-x11 dwm
#exec dwm
